name: polyfocus-bot
services:
- name: web
  source_dir: /
  github:
    repo: yourusername/polymarket-bot
    branch: main
  run_command: python start_bot.py
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8000
  health_check:
    http_path: /health
  envs:
  - key: TELEGRAM_BOT_TOKEN
    scope: RUN_TIME
    type: SECRET
  - key: ENCRYPTION_KEY
    scope: RUN_TIME
    type: SECRET
  - key: POLYMARKET_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: LIFI_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: GOOGLE_TRANSLATE_API_KEY
    scope: RUN_TIME
    type: SECRET
